### ISSUE TITLE
Pointer-wise operator with multiple inputs

### ISSUE THREAD

**Issue by erhoo82** [NVIDIA/PyProf#146]
'clamp' operator is categorized as unary point-wise op but it contains multiple inputs {input, min, max}, which meets the assert condition in the below line. 

https://github.com/NVIDIA/PyProf/blob/708b169a5cce971959ece8016419d8c9a2e579c2/pyprof/prof/pointwise.py#L148

Here is the input argument information from the parser output.

'args': [{'name': '', 'type': 'tensor', 'shape': (518400,), 'dtype': 'int64'}, {'name': '', 'type': 'int', 'value': 0}, {'name': '', 'type': 'int', 'value': 359}]}"]

**Comment by adityaiitb** [comment]
Thanks for reporting the bug and root causing it. Really appreciate it. Temporarily can you comment out the assert and reinstall. Everything should work as expected because the additional arguments like `min` and `max` are not used.

**Comment by adityaiitb** [comment]
If possible can you share the profiler output (`net.sqlite`)?

**Comment by adityaiitb** [comment]
Closing. Being fixed here https://github.com/NVIDIA/PyProf/pull/156.
