### ISSUE TITLE
Code fix

### ISSUE THREAD

**Issue by erhoo82** [NVIDIA/PyProf#147]
https://github.com/NVIDIA/PyProf/blob/708b169a5cce971959ece8016419d8c9a2e579c2/pyprof/prof/memory.py#L56-L58

The code lines in the above link should be fixed as below.

`args = list(filter(lambda x: x['name'] == "" and x['type'] == "int"), args)`
to
`args = list(filter(lambda x: x['name'] == "" and x['type'] == "int", args))`

**Comment by adityaiitb** [comment]
Thanks for spotting the error.

**Comment by adityaiitb** [comment]
Closing. Being fixed [here](https://github.com/NVIDIA/PyProf/pull/155).
