### ISSUE TITLE
Dtype mismatch when using AMP

### ISSUE THREAD

**Issue by erhoo82** [NVIDIA/PyProf#148]
https://github.com/NVIDIA/PyProf/blob/708b169a5cce971959ece8016419d8c9a2e579c2/pyprof/prof/conv.py#L155

When using APEX AMP (not PyTorch-native AMP), filter weight and bias data types are parsed as fp32, thus the above assert line breaks prof processing.

I think the precision should be somehow aligned with input precision?

**Comment by adityaiitb** [comment]
Please [see](https://github.com/NVIDIA/PyProf/blob/main/docs/faqs.rst). Did you use the correct initializing sequence?

**Comment by erhoo82** [comment]
I see. It seems that I initialized pyprof after amp initialization.

**Comment by adityaiitb** [comment]
Did the issue get resolved after the correct initialization sequence?
