### ISSUE TITLE
dtype assertion Issue

### ISSUE THREAD

**Issue by debermudez** [NVIDIA/PyProf#154]
Lines like the following: https://github.com/NVIDIA/PyProf/blob/866f71ca0dbc1d2b566ad3ff73e6fb25c82ae315/pyprof/prof/conv.py#L155
I do not think are valid anymore when using amp.autocast. 

Autocast will cast mismatched types to matching types under the hood while the network is running but the assertion will still fire during the prof stage.

**Comment by debermudez** [comment]
I think it is safe to remove these assertions now. They were more necessary before the introduction of amp to Pytorch but are now likely working off of incorrect assumptions.

Alternatively, we can try to gate these assertions based on whether amp is used as a context manager. 

@adityaiitb what do you think?

**Comment by adityaiitb** [comment]
Is this related to the initialization sequence [here](https://github.com/NVIDIA/PyProf/blob/main/docs/faqs.rst)? Do we have a repro if that is not the case. Just FYI, we monkey patched the lowest PyTorch API (`nn.functional.conv*`) and those assertions have nothing to do with AMP. The logic after that statement (calculation of bytes and flops) is contingent on `i_dtype == w_dtype`. Removing the assert will probably cause the script run to completion but will likely result in incorrect bytes and flops calculation. I am not up to speed on autocast and its possible the APIs have become more relaxed, in which case we will have to figure out what autocast does, create new assertions and the following logic.

**Comment by debermudez** [comment]
>Is this related to the initialization sequence here? Do we have a repro if that is not the case. 

This is not related to the initialization sequence. 

>The logic after that statement (calculation of bytes and flops) is contingent on i_dtype == w_dtype. Removing the assert will probably cause the script run to completion but will likely result in incorrect bytes and flops calculation. I am not up to speed on autocast and its possible the APIs have become more relaxed, in which case we will have to figure out what autocast does, create new assertions and the following logic.

We should plan to meet with the autocast contributors , but for now I think the assertion is no longer valid. It will have fall out for the bytes and flops calculations that a meeting should help clear up.

For now, are you okay with me 

- removing the assertion
- adding a note to the readme, stating that the bytes and flops calculations are being revised

**Comment by adityaiitb** [comment]
I am not ok with this. How do we know the assertion is no longer valid without a valid repro? The checks and asserts were put for a good reason. Without a repro how would we even know what is wrong and what to fix. Whoever encountered and reported the issue should follow [this](https://github.com/NVIDIA/PyProf#reporting-problems-asking-questions). If they are unwilling to share a repro, they can "fix" it locally by disabling the assert without impacting users at large.

Let's meet with the autocast folks. If autocast is indeed the reason, it will require changes to other operations e.g. mm, bmm, matmul etc.

**Comment by debermudez** [comment]
Sounds good Aditya. Let me get going on figuring that out.
