### ISSUE TITLE
Profiling dict file gives assertion error

### ISSUE THREAD

**Issue by ulorentz** [NVIDIA/PyProf#16]
I created a sql profile file with: `nvprof -f -o net.sql -- python tiny_linknet/train.py `
Then I dumped with `python -m apex.pyprof.parse net.sql > net.dict`
Trying to use pyprof with `python -m pyprof.prof --csv net.dict` I get this assertion error:
```
"Idx","Direction","Sub","Module","Op","Kernel","Params","Sil(ns)"
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/lorenzo/.local/lib/python3.8/site-packages/pyprof/prof/__main__.py", line 21, in <module>
    main()
  File "/home/lorenzo/.local/lib/python3.8/site-packages/pyprof/prof/prof.py", line 242, in main
    xx = foo(mod, op, d)
  File "/home/lorenzo/.local/lib/python3.8/site-packages/pyprof/prof/prof.py", line 84, in foo
    xx = Conv(d)
  File "/home/lorenzo/.local/lib/python3.8/site-packages/pyprof/prof/conv.py", line 155, in __init__
    assert (i['dtype'] == w['dtype'])
AssertionError
```

**Comment by debermudez** [comment]
I will have time to look at this next week. Thanks for the heads up.

**Comment by debermudez** [comment]
Would you be able to send over the sql file that was generated from nvprof? I would like to try and debug on my end more.

**Comment by ulorentz** [comment]
Hi Elias,
attached the sql file. Thanks for debugging.
Lorenzo
 net.sql
<https://drive.google.com/file/d/1vP7Yqc3XfTVThQp007I9BFHc2S9CYwm1/view?usp=drive_web>

Il giorno lun 18 mag 2020 alle ore 20:41 Elias Bermudez <
notifications@github.com> ha scritto:

**Comment by debermudez** [comment]
Is nvprof also failing for you or is it running to completion?
The output you are getting is due to the image tensor and weight tensor not being the same dtype.
AssertionError: i: float16, w: float32
I would expect this to fail in pytorch as well which would manifest as nvprof not running to completion.

**Comment by ulorentz** [comment]
No, it's not failing. It may be related to the fact I am using apex (https://github.com/NVIDIA/apex) that actually performs mixed precision training?

**Comment by debermudez** [comment]
Are you initializing amp prior to initializing pyprof?
https://github.com/NVIDIA/PyProf/blob/master/docs/faqs.rst

**Comment by ulorentz** [comment]
Now I get this error:
```
"Idx","Direction","Sub","Module","Op","Kernel","Params","Sil(ns)"
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/lorenzo/.local/lib/python3.8/site-packages/pyprof/prof/__main__.py", line 21, in <module>
    main()
  File "/home/lorenzo/.local/lib/python3.8/site-packages/pyprof/prof/prof.py", line 202, in main
    kernel = eval(line)
  File "<string>", line 1
    no such table: CUPTI_ACTIVITY_KIND_KERNEL
       ^
SyntaxError: invalid syntax
```

**Comment by ulorentz** [comment]
Furthermore this output was with pyprof.init() using apex with optimization "O0", if I use "O1" I am even not able to run the network, the error I get, during training, is this:
```
Traceback (most recent call last):
  File "tiny_linknet/train.py", line 277, in <module>
    main(args)
  File "tiny_linknet/train.py", line 229, in main
    false_positive, unnecessary = fitter.fit(args.maxepoch, 
  File "/home/lorenzo/CERN/dune-reco/tiny_linknet/utils/fit.py", line 95, in fit
    loss = self._batch_loss(xb, yb, training=True)
  File "/home/lorenzo/CERN/dune-reco/tiny_linknet/utils/fit.py", line 234, in _batch_loss
    scaled_loss.backward()
  File "/home/lorenzo/.local/lib/python3.8/site-packages/pyprof/nvtx/nvmarker.py", line 165, in wrapper_func
    result = func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/lib/python3.8/site-packages/torch/autograd/__init__.py", line 98, in backward
    Variable._execution_engine.run_backward(
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR (findAlgorithms at ../aten/src/ATen/native/cudnn/Conv.cpp:613)
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6a (0x7fe4a646ca8a in /usr/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x2fa6949 (0x7fe4a9424949 in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0x2fa87a5 (0x7fe4a94267a5 in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #3: <unknown function> + 0x2f99209 (0x7fe4a9417209 in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0x2f9b3ff (0x7fe4a94193ff in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0x2f9d6df (0x7fe4a941b6df in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #6: at::native::cudnn_convolution_backward_weight(c10::ArrayRef<long>, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool) + 0x5a (0x7fe4a941b8fa in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0x2fe3009 (0x7fe4a9461009 in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #8: <unknown function> + 0x300094b (0x7fe4a947e94b in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #9: at::native::cudnn_convolution_backward(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool, std::array<bool, 2ul>) + 0x3d5 (0x7fe4a941cc55 in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #10: <unknown function> + 0x2fe2eb2 (0x7fe4a9460eb2 in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #11: <unknown function> + 0x30009c7 (0x7fe4a947e9c7 in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
frame #12: <unknown function> + 0x31c1f28 (0x7fe4ea189f28 in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #13: <unknown function> + 0x320dc67 (0x7fe4ea1d5c67 in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #14: torch::autograd::generated::CudnnConvolutionBackward::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0x426 (0x7fe4e9d5b036 in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #15: <unknown function> + 0x32e3fdb (0x7fe4ea2abfdb in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #16: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&) + 0x1292 (0x7fe4ea2a8182 in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #17: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&, bool) + 0x62d (0x7fe4ea2a976d in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #18: torch::autograd::Engine::thread_init(int) + 0x4f (0x7fe4ea2a236f in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #19: torch::autograd::python::PythonEngine::thread_init(int) + 0x4b (0x7fe4ed30eeab in /usr/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #20: <unknown function> + 0xcfb24 (0x7fe4ef8c8b24 in /usr/lib/libstdc++.so.6)
frame #21: <unknown function> + 0x946f (0x7fe52594a46f in /usr/lib/libpthread.so.0)
frame #22: clone + 0x43 (0x7fe525e223d3 in /usr/lib/libc.so.6)

==13124== Generated result file: /home/lorenzo/CERN/dune-reco/net.sql
======== Error: Application returned non-zero code 1
```

**Comment by debermudez** [comment]
> Now I get this error:
> 
> ```
> "Idx","Direction","Sub","Module","Op","Kernel","Params","Sil(ns)"
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/home/lorenzo/.local/lib/python3.8/site-packages/pyprof/prof/__main__.py", line 21, in <module>
>     main()
>   File "/home/lorenzo/.local/lib/python3.8/site-packages/pyprof/prof/prof.py", line 202, in main
>     kernel = eval(line)
>   File "<string>", line 1
>     no such table: CUPTI_ACTIVITY_KIND_KERNEL
>        ^
> SyntaxError: invalid syntax
> ```

This error message points to nvprof not completing correctly.
NVprof will generate that table if it has information to populate into that table.

**Comment by debermudez** [comment]
> Furthermore this output was with pyprof.init() using apex with optimization "O0", if I use "O1" I am even not able to run the network, the error I get, during training, is this:
> 
> ```
> Traceback (most recent call last):
>   File "tiny_linknet/train.py", line 277, in <module>
>     main(args)
>   File "tiny_linknet/train.py", line 229, in main
>     false_positive, unnecessary = fitter.fit(args.maxepoch, 
>   File "/home/lorenzo/CERN/dune-reco/tiny_linknet/utils/fit.py", line 95, in fit
>     loss = self._batch_loss(xb, yb, training=True)
>   File "/home/lorenzo/CERN/dune-reco/tiny_linknet/utils/fit.py", line 234, in _batch_loss
>     scaled_loss.backward()
>   File "/home/lorenzo/.local/lib/python3.8/site-packages/pyprof/nvtx/nvmarker.py", line 165, in wrapper_func
>     result = func(*args, **kwargs)
>   File "/usr/lib/python3.8/site-packages/torch/tensor.py", line 198, in backward
>     torch.autograd.backward(self, gradient, retain_graph, create_graph)
>   File "/usr/lib/python3.8/site-packages/torch/autograd/__init__.py", line 98, in backward
>     Variable._execution_engine.run_backward(
> RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR (findAlgorithms at ../aten/src/ATen/native/cudnn/Conv.cpp:613)
> frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6a (0x7fe4a646ca8a in /usr/lib/python3.8/site-packages/torch/lib/libc10.so)
> frame #1: <unknown function> + 0x2fa6949 (0x7fe4a9424949 in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
> frame #2: <unknown function> + 0x2fa87a5 (0x7fe4a94267a5 in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
> frame #3: <unknown function> + 0x2f99209 (0x7fe4a9417209 in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
> frame #4: <unknown function> + 0x2f9b3ff (0x7fe4a94193ff in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
> frame #5: <unknown function> + 0x2f9d6df (0x7fe4a941b6df in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
> frame #6: at::native::cudnn_convolution_backward_weight(c10::ArrayRef<long>, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool) + 0x5a (0x7fe4a941b8fa in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
> frame #7: <unknown function> + 0x2fe3009 (0x7fe4a9461009 in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
> frame #8: <unknown function> + 0x300094b (0x7fe4a947e94b in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
> frame #9: at::native::cudnn_convolution_backward(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool, std::array<bool, 2ul>) + 0x3d5 (0x7fe4a941cc55 in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
> frame #10: <unknown function> + 0x2fe2eb2 (0x7fe4a9460eb2 in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
> frame #11: <unknown function> + 0x30009c7 (0x7fe4a947e9c7 in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
> frame #12: <unknown function> + 0x31c1f28 (0x7fe4ea189f28 in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
> frame #13: <unknown function> + 0x320dc67 (0x7fe4ea1d5c67 in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
> frame #14: torch::autograd::generated::CudnnConvolutionBackward::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0x426 (0x7fe4e9d5b036 in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
> frame #15: <unknown function> + 0x32e3fdb (0x7fe4ea2abfdb in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
> frame #16: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&) + 0x1292 (0x7fe4ea2a8182 in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
> frame #17: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&, bool) + 0x62d (0x7fe4ea2a976d in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
> frame #18: torch::autograd::Engine::thread_init(int) + 0x4f (0x7fe4ea2a236f in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
> frame #19: torch::autograd::python::PythonEngine::thread_init(int) + 0x4b (0x7fe4ed30eeab in /usr/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
> frame #20: <unknown function> + 0xcfb24 (0x7fe4ef8c8b24 in /usr/lib/libstdc++.so.6)
> frame #21: <unknown function> + 0x946f (0x7fe52594a46f in /usr/lib/libpthread.so.0)
> frame #22: clone + 0x43 (0x7fe525e223d3 in /usr/lib/libc.so.6)
> 
> ==13124== Generated result file: /home/lorenzo/CERN/dune-reco/net.sql
> ======== Error: Application returned non-zero code 1
> ```

Are you seeing this error when you run without pyprof?

**Comment by ulorentz** [comment]
> > Now I get this error:
> > ```
> > "Idx","Direction","Sub","Module","Op","Kernel","Params","Sil(ns)"
> > Traceback (most recent call last):
> >   File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
> >     return _run_code(code, main_globals, None,
> >   File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
> >     exec(code, run_globals)
> >   File "/home/lorenzo/.local/lib/python3.8/site-packages/pyprof/prof/__main__.py", line 21, in <module>
> >     main()
> >   File "/home/lorenzo/.local/lib/python3.8/site-packages/pyprof/prof/prof.py", line 202, in main
> >     kernel = eval(line)
> >   File "<string>", line 1
> >     no such table: CUPTI_ACTIVITY_KIND_KERNEL
> >        ^
> > SyntaxError: invalid syntax
> > ```
> 
> This error message points to nvprof not completing correctly.
> NVprof will generate that table if it has information to populate into that table.

Quite strange, because the program ends without error.

**Comment by ulorentz** [comment]
> > Furthermore this output was with pyprof.init() using apex with optimization "O0", if I use "O1" I am even not able to run the network, the error I get, during training, is this:
> > ```
> > Traceback (most recent call last):
> >   File "tiny_linknet/train.py", line 277, in <module>
> >     main(args)
> >   File "tiny_linknet/train.py", line 229, in main
> >     false_positive, unnecessary = fitter.fit(args.maxepoch, 
> >   File "/home/lorenzo/CERN/dune-reco/tiny_linknet/utils/fit.py", line 95, in fit
> >     loss = self._batch_loss(xb, yb, training=True)
> >   File "/home/lorenzo/CERN/dune-reco/tiny_linknet/utils/fit.py", line 234, in _batch_loss
> >     scaled_loss.backward()
> >   File "/home/lorenzo/.local/lib/python3.8/site-packages/pyprof/nvtx/nvmarker.py", line 165, in wrapper_func
> >     result = func(*args, **kwargs)
> >   File "/usr/lib/python3.8/site-packages/torch/tensor.py", line 198, in backward
> >     torch.autograd.backward(self, gradient, retain_graph, create_graph)
> >   File "/usr/lib/python3.8/site-packages/torch/autograd/__init__.py", line 98, in backward
> >     Variable._execution_engine.run_backward(
> > RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR (findAlgorithms at ../aten/src/ATen/native/cudnn/Conv.cpp:613)
> > frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6a (0x7fe4a646ca8a in /usr/lib/python3.8/site-packages/torch/lib/libc10.so)
> > frame #1: <unknown function> + 0x2fa6949 (0x7fe4a9424949 in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
> > frame #2: <unknown function> + 0x2fa87a5 (0x7fe4a94267a5 in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
> > frame #3: <unknown function> + 0x2f99209 (0x7fe4a9417209 in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
> > frame #4: <unknown function> + 0x2f9b3ff (0x7fe4a94193ff in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
> > frame #5: <unknown function> + 0x2f9d6df (0x7fe4a941b6df in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
> > frame #6: at::native::cudnn_convolution_backward_weight(c10::ArrayRef<long>, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool) + 0x5a (0x7fe4a941b8fa in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
> > frame #7: <unknown function> + 0x2fe3009 (0x7fe4a9461009 in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
> > frame #8: <unknown function> + 0x300094b (0x7fe4a947e94b in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
> > frame #9: at::native::cudnn_convolution_backward(at::Tensor const&, at::Tensor const&, at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, long, bool, bool, std::array<bool, 2ul>) + 0x3d5 (0x7fe4a941cc55 in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
> > frame #10: <unknown function> + 0x2fe2eb2 (0x7fe4a9460eb2 in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
> > frame #11: <unknown function> + 0x30009c7 (0x7fe4a947e9c7 in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so)
> > frame #12: <unknown function> + 0x31c1f28 (0x7fe4ea189f28 in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
> > frame #13: <unknown function> + 0x320dc67 (0x7fe4ea1d5c67 in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
> > frame #14: torch::autograd::generated::CudnnConvolutionBackward::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0x426 (0x7fe4e9d5b036 in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
> > frame #15: <unknown function> + 0x32e3fdb (0x7fe4ea2abfdb in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
> > frame #16: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&) + 0x1292 (0x7fe4ea2a8182 in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
> > frame #17: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&, bool) + 0x62d (0x7fe4ea2a976d in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
> > frame #18: torch::autograd::Engine::thread_init(int) + 0x4f (0x7fe4ea2a236f in /usr/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
> > frame #19: torch::autograd::python::PythonEngine::thread_init(int) + 0x4b (0x7fe4ed30eeab in /usr/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
> > frame #20: <unknown function> + 0xcfb24 (0x7fe4ef8c8b24 in /usr/lib/libstdc++.so.6)
> > frame #21: <unknown function> + 0x946f (0x7fe52594a46f in /usr/lib/libpthread.so.0)
> > frame #22: clone + 0x43 (0x7fe525e223d3 in /usr/lib/libc.so.6)
> > 
> > ==13124== Generated result file: /home/lorenzo/CERN/dune-reco/net.sql
> > ======== Error: Application returned non-zero code 1
> > ```
> 
> Are you seeing this error when you run without pyprof?

No, without pyprof it works fine.

**Comment by debermudez** [comment]
Let's focus on the sql error first.
Can you send your network code, run command, and anything else i would need to repro locally?

**Comment by ulorentz** [comment]
Can you give me an email so I can send you this stuff?

**Comment by debermudez** [comment]
Send it here: de.bermudez13@gmail.com

**Comment by debermudez** [comment]
Running locally, I running the following 3 commands. 
```
nsys profile -f true -o tiny --export sqlite python tiny_linknet/train.py  --bs 16 --aug 4 --class-bal --maxepoch 1

python -m pyprof.parse tiny.sqlite > tiny.dict

python -m pyprof.prof --csv tiny.dict > tiny.csv
```
The first 2 commands are going through just fine. Note: I am using nsight systems and not nvprof since nvprof is deprecated. 
I am getting an assertion error for the 3rd command that I am still investigating. It is related to apex not playing nice with pyprof. 

In the meantime, can you run on your end using nsight systems to see if missing sql table error goes away?

**Comment by ulorentz** [comment]
I confirm the first two commands run fine. The third gives the assertion error.

**Comment by adityaiitb** [comment]
I had assumed that only tensors of the same dtype can be added. However, that is not true as the following code shows. It triggers an assert in the prof.py script. I will fix it soon.

```
import torch
import pyprof
pyprof.init()

a = torch.ones(5,5).float().cuda()
b = torch.ones(5,5).bool().cuda()
c = a + b
```

**Comment by debermudez** [comment]
@ulorentz Pyprof has disabled the assertion that is failing.  
We have some more work to do that we will track in https://github.com/NVIDIA/PyProf/issues/26.
Can you pull the new master and test with your network? Locally, I was able to get it to execute successfully.

**Comment by ulorentz** [comment]
It works. Then I don't understand why no kernel uses tensor cores. I am using apex, and a RTX2070super, but accordingly to pyprof no kernel is executed on TC. A problem of pyprof that doesn't detect the usage or a problem of apex/nvidia?

**Comment by adityaiitb** [comment]
There are 26 kernels which use tensor cores. Grep for `s884`. Out of those, for 12 kernels (for which complete information was available) we correctly infer that tensor core was used. We will fix the output for the remaining 14 kernels. Thanks for bringing it to our notice.

From your log I see that a lot of layers have batch dimensions of 1 or 10. Also at quite a few places the channel dimension `C` is 1. While cuBLAS and cuDNN can do some padding and try to use tensor cores but its probably best to use a higher batch size (preferably a multiple of 8), say 16. `C==1` is also a corner case. While one cannot control the input channels but is there a way to tweak the network to increase the channel dimensions for the internal layers?

Let us know if with these changes you are able to see more tensor core usage and less FFT / winograd kernels.

Also, it appears you forgot to enable pytorch to emit NVTX i.e.
```
with torch.autograd.profiler.emit_nvtx():
```
as shown here: https://github.com/NVIDIA/PyProf/blob/master/docs/profile.rst

**Comment by adityaiitb** [comment]
Please see Nvidia's performance documentation. Its a long read but here is the important bit.

From https://docs.nvidia.com/deeplearning/performance/dl-performance-convolutional/index.html#channels

"Using Tensor Cores on Volta requires that C and K be multiples of 8 in FP16 or 16 in INT8. A caveat applies here: currently, for NCHW-packed FP16 data, channels will be automatically padded to multiples of 8 such that tensor cores will be enabled."

In your case `C==1` at quite a few instances which is preventing tensor core usage.

**Comment by ulorentz** [comment]
Only the first layer has channel = 1, since the images have one channel. All the inner layers already have channels multiples of 8. Maybe this network doesn't fit the requirement, but still I found odd the fact that with apex optimization "O0" is faster than "O1".

**Comment by adityaiitb** [comment]
W.r.t. tensor core usage, I can take a look if you are ok with sharing the model running with synthetic data.

W.r.t. Apex optimization levels, I would suggest filing a bug on the APEX repo.

**Comment by ulorentz** [comment]
Can you share me your email so I can send the necessary files?

**Comment by debermudez** [comment]
@ulorentz What is the status of this issue at this point? Are you ungated or is there still an issue?

**Comment by debermudez** [comment]
Closing due to lack of response.
