### ISSUE TITLE
Is there any update on TensorCores eligible kernel list?

### ISSUE THREAD

**Issue by gaoteng-git** [NVIDIA/PyProf#170]
@matthewkotila @debermudez
The Tensor Cores eligible kernel list is 1.5 years old. https://github.com/NVIDIA/PyProf/blob/fd1b2902e3306119eee40ba6b6e8b2f816920c29/pyprof/prof/tc.py#L20-L24  I'm not sure whether there are new updates together with new coming chips or instruction set in latest year. 
How could I get latest list of kernel name eligible for Tensor Cores? Is there any official doc that describes which kernel name patterns are Tensor Cores eligible?
Thanks a lot!

**Comment by debermudez** [comment]
Hey Teng. As of June 30th 2021, Nvidia stopped making contributions to this repository. 
Alternative options can be found in the readme [here](https://github.com/NVIDIA/PyProf/blob/main/README.rst).
All the best!
