### ISSUE TITLE
Pyprof assertions are too restrictive

### ISSUE THREAD

**Issue by debermudez** [NVIDIA/PyProf#26]
In parts of the codebase, there are assertions that are now too restrictive.
For example, 
https://github.com/NVIDIA/PyProf/blob/a983b171bee7513a1d9cd3cc661f2f7c18e4db2d/pyprof/prof/pointwise.py#L161
requires that the dtype of the 2 tensors are the same. This is not required in pytorch. The assertions need to be reviewed. 
This can also have deeper changes to the byte and flop calculations given the assumption that the dtypes were the same is not true.

**Comment by adityaiitb** [comment]
@debermudez Do you happen to have the profile which triggered the assertions? The problem should have resolved after the refactoring.

**Comment by adityaiitb** [comment]
This has been fixed. Closing.
