### ISSUE TITLE
pyprof and nsight

### ISSUE THREAD

**Issue by ethem-kinginthenorth** [NVIDIA/PyProf#35]
How would I use nsight to visualize pyprof (using nvprof) outputs?

**Comment by adityaiitb** [comment]
NVprof and Nsight have different file formats and you cannot use Nsight to visualize if you used NVprof to profile. Just to provide more information.

The tool flow is:
1. pyprof.init()     # This annotates all pytorch calls with their tensor shapes, datatypes etc.
2. Use NVprof / Nsight to profile.
3. Call `pyprof.parse` and `pyprof.prof` to "post-process" all the information.

After step 2, you can open the corresponding file in NVprof or Nsight and you will be able to see all the annotations (in the form of NVTX range markers). Note that the annotations can be verbose.

In step 3, we extract+post process the information to calculate direction, bytes, flops, tensor core usage etc. This information does not show up in any profiler (nvprof / nsight).

Hope this clarifies the tool flow.

**Comment by ethem-kinginthenorth** [comment]
@adityaiitb thanks for the information. So can I directly replace nvprof with nsight to get a qdrep file. E.g., nsight -o prof.qdrep python mypythonfile.py ?

**Comment by ethem-kinginthenorth** [comment]
@adityaiitb thanks again for the information.
I run my code using nsys. I am also getting a qdrep file where I can use nsigh tool to visualize.

Now I have one more question :)

I am seeing something like below in the terminal, is that normal?

Sent signal 15 (Terminated) to target application's process group ID = 5840.
Use the kill option to modify this behavior.

Importing [===============================================================100%]
The application process terminated. One or more process it created re-parented. Waiting for termination of re-parented processes. To modify this behavior, use the `--wait` option.

The target application terminated with signal 15 (SIGTERM)

**Comment by adityaiitb** [comment]
Sorry, no clue. I would suggest asking in the [Nvidia Developer Forum](https://forums.developer.nvidia.com/).

**Comment by ethem-kinginthenorth** [comment]
@adityaiitb thanks. closing the issue.
