### ISSUE TITLE
pyprof.init() leaks

### ISSUE THREAD

**Issue by ethem-kinginthenorth** [NVIDIA/PyProf#39]
I have realized that having pyprof.init() in the code causes memory accumulation possibly due to a leak. When I remove pyprof.init() then memory is stabilized.

**Comment by adityaiitb** [comment]
Did you observe this leak on the CPU or GPU? Do you have a repro? Note that, pyprof captures dynamic information for every torch API call so I would expect its CPU memory usage to grow over time.

**Comment by ethem-kinginthenorth** [comment]
this is GPU memory. I realized as I saw low utilization warning in the profiler. Then I wanted to increase the batch_size, I realized that at each step, the memory is increasing. When I removed. pyprof.init(), then the memory was stabilized. 

In order to repo:
here is the notebook: https://github.com/NVIDIA/NeMo/blob/master/examples/nlp/token_classification/PunctuationWithBERT.ipynb

I converted the notebook into a standalone python file. Then replace belo:
`nf.train(tensors_to_optimize=[task_loss],
         callbacks=[callback_train, callback_eval, ckpt_callback],
         lr_policy=lr_policy,
         batches_per_step=BATCHES_PER_STEP,
         optimizer=OPTIMIZER,
         optimization_params={"num_epochs": NUM_EPOCHS,
                              "lr": LEARNING_RATE})`

with

`with torch.autograd.profiler.emit_nvtx():
    profiler.start()
    nf.train(tensors_to_optimize=[task_loss],
         callbacks=[callback_train],
         lr_policy=lr_policy,
         batches_per_step=BATCHES_PER_STEP,
         optimizer=OPTIMIZER,
         optimization_params={"num_epochs": NUM_EPOCHS,
                              "lr": LEARNING_RATE})
         profiler.stop()
` 

and also added these:
`
import torch
import torch.cuda.profiler as profiler
import pyprof
pyprof.init()
`

**Comment by adityaiitb** [comment]
Can you comment out this line : https://github.com/NVIDIA/PyProf/blob/master/pyprof/nvtx/nvmarker.py#L124, reinstall and rerun and see if the problem goes away.

**Comment by ethem-kinginthenorth** [comment]
sure. let me try and get back to you. thanks

**Comment by ethem-kinginthenorth** [comment]
It does help some. It used to error out at 19th step, now it errored out at the 25th step.

For a reference, without pyprof.init(), I can use a batch size of 768, whereas with pyprof.init() it does not complete with a batch size of 128 due to not enough memory (I am using a v100 16gb card).

**Comment by ethem-kinginthenorth** [comment]
ok. I forget to reinstall. let me try reinstalling as well.

**Comment by ethem-kinginthenorth** [comment]
ok. that worked.

**Comment by adityaiitb** [comment]
Great! For now please use this fix while we investigate.

**Comment by adityaiitb** [comment]
@debermudez I was able to reproduce the OOM issue on a simple NCF benchmark. The problem goes away when https://github.com/NVIDIA/PyProf/blob/master/pyprof/nvtx/nvmarker.py#L124 is commented out. [Here](https://github.com/adityaiitb/dlperf/tree/master/NCF) is the code and instructions for reproducing the issue.
