### ISSUE TITLE
Move installation and simple usage to the landing page.

### ISSUE THREAD

**Issue by adityaiitb** [NVIDIA/PyProf#52]
Most users care about installation and simple usage instructions and so that should be on the landing page.
The contributing and asking questions can be moved to docs (with just a hyperlink on the landing page).

**Comment by dzier** [comment]
Are you talking about the main README? The README and docs are set up to conform with other major NVIDIA released products, such as [Triton Inference Server](https://github.com/NVIDIA/triton-inference-server). We moved all important docs into the /docs section. 

However, I do see the use case for adding installation and quickstart to the README. I will need to play around with the documentation to see what is possible.

**Comment by adityaiitb** [comment]
Yup, I meant the main README.

**Comment by dzier** [comment]
Instructions are now in the main README.
