### ISSUE TITLE
Add GTC presentation to docs.

### ISSUE THREAD

**Issue by adityaiitb** [NVIDIA/PyProf#55]
Update GTC presentation slides with correct links and add to docs.

**Comment by dzier** [comment]
If anything, the presentation should be converted into a proper User Guide. We should not add slides to the docs. We can add al link to the actual presentation though.

Aditya, please note that the user guide is now an actual living document that gets built with each release. All the RST files are in the docs. We cannot add a presentation and have the built properly for a user guide.

**Comment by dzier** [comment]
https://github.com/NVIDIA/PyProf/pull/64 should cover this request.

**Comment by dzier** [comment]
Links to the presentation are now in the README and the User Guide has been updated to including missing information from the slides. Closing issue. If there is anything else that you see missing, let me know or file another ticket.
