### ISSUE TITLE
another assertion fired

### ISSUE THREAD

**Issue by ethem-kinginthenorth** [NVIDIA/PyProf#68]
This one is also related with the previous one. I am just changing tf32->amp. The model is resnet50 from nvidia deeplearningexamples repo. 

11 fprop 0 torch.nn.functional max_pool2d max_pool_forward_nchw T=[(512,64,112,112)],['float16'] 2202121
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/ecan/PyProf/pyprof/prof/__main__.py", line 21, in <module>
    main()
  File "/ecan/PyProf/pyprof/prof/prof.py", line 242, in main
    xx = foo(mod, op, d)
  File "/ecan/PyProf/pyprof/prof/prof.py", line 84, in foo
    xx = Conv(d)
  File "/ecan/PyProf/pyprof/prof/conv.py", line 155, in __init__
    assert (i['dtype'] == w['dtype'])
AssertionError

**Comment by adityaiitb** [comment]
Did you use the correct initialization sequence of AMP and PyProf? See the second FAQ question [here](https://github.com/NVIDIA/PyProf/blob/master/docs/faqs.rst)

If yes, can you provide a simple standalone repro. Its possible PyProf does not correctly infer the new tf32 datatype.

**Comment by ethem-kinginthenorth** [comment]
@adityaiitb I didn't know that there is an order to initialize amp. I have just injected pyprof into nvidia deep learning examples resnet50 example. Let me check what is the order. Thanks.

**Comment by adityaiitb** [comment]
AFAIU AMP and PyProf use similar code interception techniques and so one has to be a little careful. Also as noted in the FAQs, PyProf can interfere with JIT/tracing and so it should be enabled after any JITting has finished.

**Comment by ethem-kinginthenorth** [comment]
I thought I init pyprof before amp but now I am getting the error below, do you think it is still related with the init order:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/ecan/PyProf/pyprof/prof/__main__.py", line 21, in <module>
    main()
  File "/ecan/PyProf/pyprof/prof/prof.py", line 244, in main
    bytes = xx.bytes()
  File "/ecan/PyProf/pyprof/prof/pointwise.py", line 233, in bytes
    return self.elems() * Utility.typeToBytes(self.type)
  File "/ecan/PyProf/pyprof/prof/pointwise.py", line 208, in elems
    assert False
AssertionError

**Comment by ethem-kinginthenorth** [comment]
```
   if args.pyprof:
        pyprof.init()

    if args.amp:
        model_and_loss, optimizer = amp.initialize(
            model_and_loss,
            optimizer,
            opt_level="O1",
            loss_scale="dynamic" if args.dynamic_loss_scale else args.static_loss_scale,
        )

```

I have the above init order

**Comment by adityaiitb** [comment]
This error is not due to the init order. This is due to some (previously unseen) binary operator which fell through the if-else block. If you can, please share the `.sql` file.

**Comment by ethem-kinginthenorth** [comment]
Here is the sql file. Thanks
[resnet50_pytorch_amp_b784.zip](https://github.com/NVIDIA/PyProf/files/5097081/resnet50_pytorch_amp_b784.zip)

**Comment by adityaiitb** [comment]
It appears you are using PyTorch 1.6. This error is the same as https://github.com/NVIDIA/PyProf/issues/46 i.e. incorrect fprop and bprop correlation. In this instance, the bprop of `relu` (sequence number 1666) is incorrectly associated with fprop of `__iadd__` (also sequence number 1666). I am glad the assertion caught it.

**Comment by ethem-kinginthenorth** [comment]
@adityaiitb thanks. then not much to do here. closing the issue.
