### ISSUE TITLE
Function trace source correlation missing

### ISSUE THREAD

**Issue by trinayan** [NVIDIA/PyProf#76]
Thank you for the great tool.  I am trying to use the tracing feature to correlate kernels to source code. When I do that, it seems some of the kernels are not getting correlated to any source line and have a empty string next to them. Is there any way to resolve this?. I can file a separate issue with the steps to reproduce if needed. But I just wanted to check if this is expected behavior and if there are any suggestions to resolve it.

**Comment by adityaiitb** [comment]
At its heart, the tool intercepts Python code (PyTorch's Python APIs) but there are many cases where a kernel is launched in the PyTorch C++ backend (e.g. bias gradient if I remember right) which we cannot intercept and hence we have no information (file_name, line_number, tensor_shape, datatype etc.).

Its a long standing gap in our tool. If you can create a small repro, we can revisit the issue.

**Comment by trinayan** [comment]
Sure. Thank you.  I will create a separate issue with all the steps
