### ISSUE TITLE
Prof script error.

### ISSUE THREAD

**Issue by wangxiang2713** [NVIDIA/PyProf#95]
Hi, i tried to run the lenet demo, and got error:
```
[hadoop-hdp@zf-data-hdp-dn-gpu069 examples]$ python3 -m pyprof.prof --csv lenet.dict > lenet.csv
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/pyprof/prof/__main__.py", line 21, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/pyprof/prof/prof.py", line 202, in main
    kernel = eval(line)
  File "<string>", line 1
    unrecognized token: "0x1000000"
                     ^
SyntaxError: invalid syntax
```

Then i find the lenet.dict only contain:
```
unrecognized token: "0x1000000"
```

Any suggestion? Thankyou very much!

**Comment by adityaiitb** [comment]
hi,

1. What is the size of the SQL file which was generated?
2. When you ran `pyprof.parse` did you see something like `Found 0 kernels. Exiting` ?

Can you share the commands you used to
a) Profile (nvprof or nsight)
b) Generate the dict.

**Comment by wangxiang2713** [comment]
> hi,
> 
> 1. What is the size of the SQL file which was generated?
> 2. When you ran `pyprof.parse` did you see something like `Found 0 kernels. Exiting` ?
> 
> Can you share the commands you used to
> a) Profile (nvprof or nsight)
> b) Generate the dict.

Hi, thankyou for your response.
1. the size of the SQL file lenet.sqlite is 7.8M
2. When i ran `pyprof.parse` nothing was printed

all my commands are
```
cd pyprof/examples
nsys profile -f true -o lenet --export sqlite python3 lenet.py
python3 -m pyprof.parse lenet.sqlite > lenet.dict
python3 -m pyprof.prof --csv lenet.dict > lenet.csv
```

By the way, my environment is:
- pytorch 1.6
- cuda 10.2
- centos 7
When i ran `pip3 list | grep pyprof`, i got:
```
nvidia-pyprof (3.6.0)
```
When i ran `nsys --version`, i got:
```
NVIDIA Nsight Systems version 2020.4.1.126-d2d452d
```

**Comment by adityaiitb** [comment]
The lenet [code](https://github.com/NVIDIA/PyProf/blob/master/pyprof/examples/lenet.py#L77-L82) uses the `profiler.start()` and `profiler.stop()` API, so please try profiling using

```python
nsys profile -f true -o lenet \
    -c cudaProfilerApi -s none \
    --stop-on-range-end true \
    --export sqlite python3 lenet.py
```

Let me know if this works.

**Comment by wangxiang2713** [comment]
> The lenet [code](https://github.com/NVIDIA/PyProf/blob/master/pyprof/examples/lenet.py#L77-L82) uses the `profiler.start()` and `profiler.stop()` API, so please try profiling using
> 
> ```python
> nsys profile -f true -o lenet \
>     -c cudaProfilerApi -s none \
>     --stop-on-range-end true \
>     --export sqlite python3 lenet.py
> ```
> 
> Let me know if this works.

Hi, thankyou for your response.
I tried that but it fail to work.

**Comment by adityaiitb** [comment]
- Are you able to run just `python3 lenet.py` i.e. without the profiler?
- What is the error when you run it with `nsys`?
- What is the output of `nvidia-smi`? Is the CUDA driver up to date?

**Comment by wangxiang2713** [comment]
> * python3 lenet.py

Hi, thankyou for your response.
- When i ran just python3 lenet.py i got this:
```
$ python3 lenet.py
Initializing NVTX monkey patches
Done with NVTX monkey patching
```
- I didn't get error information when i ran it with nsys

- the output of nvidia-smi is:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.51.06    Driver Version: 450.51.06    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:3B:00.0 Off |                    0 |
| N/A   35C    P8    10W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by adityaiitb** [comment]
Weird. Can you share the `lenet.sqlite` file you obtained (Google drive etc.). I tested Lenet on a Turing T4 and it works fine for me.

**Comment by wangxiang2713** [comment]
> Weird

[lenet.sqlite.zip](https://github.com/NVIDIA/PyProf/files/5363884/lenet.sqlite.zip)
Thank you very much!

**Comment by adityaiitb** [comment]
The SQL file you sent is only 438 KB not 7 MB. I just did a clean install and tested the SQL file you sent and everything works as expected. I did

```bash
python3 -m pyprof.parse lenet.sqlite > lenet.dict
```
and this prints the following as expected.
```
Found 54 kernels. Getting info for each kernel.
```
The `lenet.dict` also contains valid data as expected. Let me know how can we resolve this.

**Comment by wangxiang2713** [comment]
> The SQL file you sent is only 438 KB not 7 MB. I just did a clean install and tested the SQL file you sent and everything works as expected. I did
> 
> ```shell
> python3 -m pyprof.parse lenet.sqlite > lenet.dict
> ```
> 
> and this prints the following as expected.
> 
> ```
> Found 54 kernels. Getting info for each kernel.
> ```
> 
> The `lenet.dict` also contains valid data as expected. Let me know how can we resolve this.

Hi, thank you for your response.
Weird. I also tried:
```
python3 -m pyprof.parse lenet.sqlite > lenet.dict
```
However, nothing printed and only 'unrecognized token: "0x1000000"'

**Comment by adityaiitb** [comment]
Can you may be try installing on a different machine (without docker, without conda)? Once you have the SQL file, you can run `parse` and `prof` on any machine (doesn't require a GPU).

**Comment by adityaiitb** [comment]
Any luck on a different machine?

**Comment by Hello-Pytorch** [comment]
> Any luck on a different machine

Weird. I failed on another CUDA 10.0 machine, but i succeed on my MAC.

**Comment by wangxiang2713** [comment]
> Any luck on a different machine?

Weird. I failed on another CUDA 10.0 machine, but i succeed on my MAC.

**Comment by adityaiitb** [comment]
Great! My guess is there is some Python / Python library / $PATH / $PYTHONPATH issue in your docker / virtualenv. Do you use [Nvidia's PyTorch docker](https://ngc.nvidia.com/catalog/containers/nvidia:pytorch)? Closing this issue, but please let us know if you run into other issues. If you can identify the source of the error please let us know.
