### ISSUE TITLE
Dependency on Nvidia nsys

### ISSUE THREAD

**Issue by adityaiitb** [NVIDIA/PyProf#99]
I don't think we should add a dependency on `nsys` [here](https://github.com/NVIDIA/PyProf/blob/master/requirements/requirements_nsys.txt). The tool does not depends on it.

**Comment by debermudez** [comment]
This is an optional requirements to support the pip wheel installation.  
If you do `pip install pyprof` it will only install pyprof. You need to explicitly call out `pip install "pyprof[nsys]"` for the nsys cli to also get installed.

**Comment by adityaiitb** [comment]
Sure, I understand, but installation of GPU/CUDA related libraries/tools is not (and should not be) in the scope of this tool.

**Comment by debermudez** [comment]
That is why it is contained in a different requirements file. The default one that most will use, is operating in the manner you suggested. This extra requirements file, is strictly to facilitate installation for a subset of users.   
This does not break or inhibit users currently using the tool. It only makes it easier for users that want nsight systems installed alongside pyprof.
